site_name: UI5 Antares
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono    
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: indigo
      accent: lime

nav:
  - UI5 Antares: index.md
  - Entry Create: entry_create.md
  - Entry Update: entry_update.md
  - Entry Delete: entry_delete.md
  - Entry Read: entry_read.md
  - Value Help: value_help.md
  - Fragment Class: fragment_class.md
  - Promisified OData V2 Classes: odata_classes.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hasanciftci26
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hasan-%C3%A7ift%C3%A7i-4b3646170

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true        

repo_url: https://github.com/hasanciftci26/ui5-antares
repo_name: ui5-antares

copyright: >
  &copy; 2024 <a href="https://github.com/hasanciftci26" target="_blank" rel="noopened">Hasan Ciftci</a>